"""Simulator-neutral replay fidelity contracts and audit tooling."""

from .contracts import (
    ContractVerdict,
    ObservationRecord,
    ReplayAdapter,
    Snapshot,
    StepRecord,
    TrajectoryRecord,
)
from .envelope import (
    BootstrapInterval,
    BranchComparison,
    BranchErrorProfile,
    CounterfactualAudit,
    ErrorDirection,
    FidelityEnvelope,
    FidelityGateResult,
    FidelityGateStatus,
    FidelityPoint,
    FrontierStatus,
    ObservedFidelityFrontier,
    RestoreProtocolComparison,
    SeedSummary,
    audit_counterfactual_fidelity,
    compare_restore_protocols,
    evaluate_fidelity_gate,
    fidelity_envelope,
    first_untrusted_horizon,
    seed_cluster_bootstrap,
    summarize_by_seed,
    summarize_error_direction,
    validate_branch_comparisons,
)
from .io import (
    EvidenceManifest,
    LoadedBranchComparisons,
    build_evidence_manifest,
    load_branch_comparisons,
    normalize_branch_comparison,
)

__all__ = [
    "ContractVerdict",
    "ObservationRecord",
    "ReplayAdapter",
    "Snapshot",
    "StepRecord",
    "TrajectoryRecord",
    "BootstrapInterval",
    "BranchComparison",
    "BranchErrorProfile",
    "CounterfactualAudit",
    "ErrorDirection",
    "EvidenceManifest",
    "FidelityEnvelope",
    "FidelityGateResult",
    "FidelityGateStatus",
    "FidelityPoint",
    "FrontierStatus",
    "LoadedBranchComparisons",
    "ObservedFidelityFrontier",
    "RestoreProtocolComparison",
    "SeedSummary",
    "audit_counterfactual_fidelity",
    "build_evidence_manifest",
    "compare_restore_protocols",
    "evaluate_fidelity_gate",
    "fidelity_envelope",
    "first_untrusted_horizon",
    "load_branch_comparisons",
    "normalize_branch_comparison",
    "seed_cluster_bootstrap",
    "summarize_by_seed",
    "summarize_error_direction",
    "validate_branch_comparisons",
]
